services:
  - type: web
    name: peerconnect-signaling
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'
